path = "/Users/monty/.espressif"
idf_path = "/Users/monty/.espressif/v6.0.2/esp-idf"
esp_idf_json_path = "/Users/monty/.espressif/tools"
tool_download_folder_name = "/Users/monty/.espressif/dist"
tool_install_folder_name = "/Users/monty/.espressif/tools"
target = ["all"]
idf_versions = ["v6.0.2"]
tools_json_file = "tools/tools.json"
config_file_save_path = "eim_config.toml"
non_interactive = true
wizard_all_questions = false
mirror = "https://github.com"
idf_mirror = "https://github.com"
pypi_mirror = "https://pypi.org/simple"
recurse_submodules = true
install_all_prerequisites = false
skip_prerequisites_check = false
cleanup = false
skip_components_download = false
python_env_folder_name = "python"
use_local_archive = "/Users/monty/Library/Application Support/eim/offline_archives/archive_v6.0.2_macos-aarch64.zst"
activation_script_path_override = "/Users/monty/.espressif/tools"
python_version_override = "python313"
create_bat_activation_script = false
