/**
 * @file ui_fonts.h
 *
 * M3 CJK bitmap fonts for the firmware build.
 *
 * The macOS simulator renders CJK via tiny_ttf from a system .ttf; on the
 * device there is no filesystem font, so the same glyph set is baked into
 * two 4bpp bitmap fonts generated by lv_font_conv (see fonts/gen_fonts.sh):
 *
 *   font_cjk_16  -> FONT_SIZE_SM (body text)
 *   font_cjk_20  -> FONT_SIZE_LG (headings / hero values)
 *
 * Glyph coverage = every character referenced by the src/ui C files plus ASCII
 * printables, Chinese punctuation and ℃/°/% (fonts/symbols.txt). When the
 * UI source gains new wording, re-run gen_fonts.sh to refresh coverage.
 *
 * The page modules accept NULL fonts and fall back to Montserrat, so a
 * build with the font .c files removed still links only if the externs
 * below are gone as well - keep this header and CMakeLists SRCS in sync.
 */

#ifndef UI_FONTS_H
#define UI_FONTS_H

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Defined in fonts/font_cjk_16.c / fonts/font_cjk_20.c (lv_font_conv). */
extern const lv_font_t font_cjk_16;
extern const lv_font_t font_cjk_20;

/**
 * Fetch the injected CJK fonts in the same (sm, lg) signature the page
 * create functions expect. Never returns NULL in the firmware build; the
 * NULL-fallback paths in the pages remain as defense in depth.
 */
static inline void ui_fonts_get(const lv_font_t ** font_sm,
                                const lv_font_t ** font_lg)
{
    if(font_sm != NULL) *font_sm = &font_cjk_16;
    if(font_lg != NULL) *font_lg = &font_cjk_20;
}

#ifdef __cplusplus
}
#endif

#endif /* UI_FONTS_H */
