/**
 * @file ui_fonts.h
 *
 * M3 CJK bitmap fonts for the firmware build.
 *
 * The macOS simulator renders CJK via tiny_ttf from a system .ttf; on the
 * device there is no filesystem font, so the same glyph set is baked into
 * two 4bpp bitmap fonts generated by lv_font_conv (see fonts/gen_fonts.sh):
 *
 *   font_cjk_16  -> FONT_SIZE_SM (body text)
 *   font_cjk_20  -> FONT_SIZE_LG (headings / hero values)
 *
 * Glyph coverage = every character referenced by the src/ui C files plus ASCII
 * printables, Chinese punctuation and ℃/°/% (fonts/symbols.txt). When the
 * UI source gains new wording, re-run gen_fonts.sh to refresh coverage.
 *
 * The page modules accept NULL fonts and fall back to Montserrat, so a
 * build with the font .c files removed still links only if the externs
 * below are gone as well - keep this header and CMakeLists SRCS in sync.
 */

#ifndef UI_FONTS_H
#define UI_FONTS_H

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Defined in fonts/font_cjk_16.c / font_cjk_20.c / font_num_34.c (lv_font_conv). */
extern const lv_font_t font_cjk_16;
extern const lv_font_t font_cjk_20;
/** 30px **纯数字**读数（工业 HMI 大读数，2026-09-18）。
 *  原为 34px，因「9376 件」这样的四位数字在 142px 卡宽里过挤，收小到 30px。
 *
 * ⚠️ 刻意不含中文字形（子集仅 18 个符号，约 23KB 源码）。
 *    大读数旁的单位（件 / 单）必须用 font_cjk_16 单独绘制；
 *    若要在 34px 里直接排版中文，需把该字加进 gen_fonts.sh 的 NUM_SYMBOLS
 *    并重新生成，否则会渲染成缺字方块。 */
extern const lv_font_t font_num_30;

/**
 * Fetch the injected CJK fonts in the same (sm, lg) signature the page
 * create functions expect. Never returns NULL in the firmware build; the
 * NULL-fallback paths in the pages remain as defense in depth.
 */
static inline void ui_fonts_get(const lv_font_t ** font_sm,
                                const lv_font_t ** font_lg)
{
    if(font_sm != NULL) *font_sm = &font_cjk_16;
    if(font_lg != NULL) *font_lg = &font_cjk_20;
}

/** 34px 纯数字读数字体。单独提供而不是塞进 ui_fonts_get，
 *  以免改动所有既有的页面签名（读数是新样式才需要的东西）。 */
static inline const lv_font_t * ui_fonts_num(void)
{
    return &font_num_30;
}

#ifdef __cplusplus
}
#endif

#endif /* UI_FONTS_H */
